#!/bin/bash
# Quick Environment Variables Checklist
# This script provides a checklist format for manual verification

echo "🔐 Environment Variables Checklist for Production Deployment"
echo "============================================================"
echo ""

echo "📋 BACKEND (Heroku) - Required Variables:"
echo "  [ ] FRONTEND_URL=https://1kappa.com"
echo "  [ ] DATABASE_URL=postgresql://..."
echo "  [ ] STRIPE_SECRET_KEY=sk_live_..."
echo "  [ ] STRIPE_WEBHOOK_SECRET=whsec_..."
echo "  [ ] AWS_ACCESS_KEY_ID=..."
echo "  [ ] AWS_SECRET_ACCESS_KEY=..."
echo "  [ ] AWS_S3_BUCKET_NAME=..."
echo "  [ ] AWS_REGION=us-east-1"
echo "  [ ] FROM_EMAIL=noreply@1kappa.com"
echo "  [ ] COGNITO_USER_POOL_ID=us-east-1_..."
echo "  [ ] COGNITO_CLIENT_ID=..."
echo "  [ ] COGNITO_REGION=us-east-1"
echo ""

echo "📋 FRONTEND (Vercel) - Required Variables:"
echo "  [ ] NEXT_PUBLIC_API_URL=https://your-app.herokuapp.com"
echo "  [ ] NEXT_PUBLIC_COGNITO_USER_POOL_ID=us-east-1_..."
echo "  [ ] NEXT_PUBLIC_COGNITO_CLIENT_ID=..."
echo "  [ ] NEXT_PUBLIC_COGNITO_REGION=us-east-1"
echo "  [ ] NEXTAUTH_SECRET=(generate with: openssl rand -base64 32)"
echo "  [ ] NEXTAUTH_URL=https://1kappa.com"
echo ""

echo "📋 GITHUB ACTIONS - Required Secrets:"
echo "  [ ] VERCEL_TOKEN"
echo "  [ ] HEROKU_API_KEY"
echo "  [ ] HEROKU_STAGING_API_KEY"
echo "  [ ] HEROKU_APP_NAME"
echo "  [ ] HEROKU_STAGING_APP_NAME"
echo "  [ ] HEROKU_EMAIL"
echo "  [ ] DATABASE_HOST"
echo "  [ ] DATABASE_USERNAME"
echo "  [ ] DATABASE_PASSWORD"
echo "  [ ] DATABASE_NAME"
echo "  [ ] STAGING_DATABASE_HOST"
echo "  [ ] STAGING_DATABASE_USERNAME"
echo "  [ ] STAGING_DATABASE_PASSWORD"
echo "  [ ] STAGING_DATABASE_NAME"
echo ""

echo "💡 Quick Commands:"
echo "  • Check Heroku vars: heroku config --app YOUR_APP"
echo "  • Check Vercel vars: cd frontend && vercel env ls"
echo "  • Generate NextAuth secret: openssl rand -base64 32"
echo ""

