/**
 * Professional industries list for registration forms
 * Used in member registration and other professional information forms
 */
export const PROFESSIONAL_INDUSTRIES = [
  { id: 'accounting', label: 'Accounting', value: 'Accounting' },
  { id: 'advertising', label: 'Advertising', value: 'Advertising' },
  { id: 'aerospace', label: 'Aerospace', value: 'Aerospace' },
  { id: 'agriculture', label: 'Agriculture', value: 'Agriculture' },
  { id: 'architecture', label: 'Architecture', value: 'Architecture' },
  { id: 'automotive', label: 'Automotive', value: 'Automotive' },
  { id: 'banking', label: 'Banking', value: 'Banking' },
  { id: 'biotechnology', label: 'Biotechnology', value: 'Biotechnology' },
  { id: 'broadcasting', label: 'Broadcasting', value: 'Broadcasting' },
  { id: 'chemical', label: 'Chemical', value: 'Chemical' },
  { id: 'civil-engineering', label: 'Civil Engineering', value: 'Civil Engineering' },
  { id: 'communications', label: 'Communications', value: 'Communications' },
  { id: 'computer-hardware', label: 'Computer Hardware', value: 'Computer Hardware' },
  { id: 'computer-software', label: 'Computer Software', value: 'Computer Software' },
  { id: 'consulting', label: 'Consulting', value: 'Consulting' },
  { id: 'construction', label: 'Construction', value: 'Construction' },
  { id: 'consumer-goods', label: 'Consumer Goods', value: 'Consumer Goods' },
  { id: 'cybersecurity', label: 'Cybersecurity', value: 'Cybersecurity' },
  { id: 'data-science', label: 'Data Science', value: 'Data Science' },
  { id: 'education', label: 'Education', value: 'Education' },
  { id: 'energy', label: 'Energy', value: 'Energy' },
  { id: 'engineering', label: 'Engineering', value: 'Engineering' },
  { id: 'entertainment', label: 'Entertainment', value: 'Entertainment' },
  { id: 'environmental', label: 'Environmental', value: 'Environmental' },
  { id: 'fashion', label: 'Fashion', value: 'Fashion' },
  { id: 'finance', label: 'Finance', value: 'Finance' },
  { id: 'food-beverage', label: 'Food & Beverage', value: 'Food & Beverage' },
  { id: 'government', label: 'Government', value: 'Government' },
  { id: 'healthcare', label: 'Healthcare', value: 'Healthcare' },
  { id: 'hospitality', label: 'Hospitality', value: 'Hospitality' },
  { id: 'human-resources', label: 'Human Resources', value: 'Human Resources' },
  { id: 'insurance', label: 'Insurance', value: 'Insurance' },
  { id: 'investment-banking', label: 'Investment Banking', value: 'Investment Banking' },
  { id: 'legal', label: 'Legal', value: 'Legal' },
  { id: 'logistics', label: 'Logistics', value: 'Logistics' },
  { id: 'manufacturing', label: 'Manufacturing', value: 'Manufacturing' },
  { id: 'marketing', label: 'Marketing', value: 'Marketing' },
  { id: 'media', label: 'Media', value: 'Media' },
  { id: 'medical-devices', label: 'Medical Devices', value: 'Medical Devices' },
  { id: 'nonprofit', label: 'Nonprofit', value: 'Nonprofit' },
  { id: 'pharmaceuticals', label: 'Pharmaceuticals', value: 'Pharmaceuticals' },
  { id: 'philanthropy', label: 'Philanthropy', value: 'Philanthropy' },
  { id: 'public-relations', label: 'Public Relations', value: 'Public Relations' },
  { id: 'real-estate', label: 'Real Estate', value: 'Real Estate' },
  { id: 'retail', label: 'Retail', value: 'Retail' },
  { id: 'sales', label: 'Sales', value: 'Sales' },
  { id: 'social-services', label: 'Social Services', value: 'Social Services' },
  { id: 'sports', label: 'Sports', value: 'Sports' },
  { id: 'telecommunications', label: 'Telecommunications', value: 'Telecommunications' },
  { id: 'transportation', label: 'Transportation', value: 'Transportation' },
  { id: 'travel', label: 'Travel', value: 'Travel' },
  { id: 'utilities', label: 'Utilities', value: 'Utilities' },
  { id: 'venture-capital', label: 'Venture Capital', value: 'Venture Capital' },
  { id: 'other', label: 'Other', value: 'Other' },
] as const;

