import { StyleSheet } from "react-native";

import { COLORS } from "../lib/constants";

import { SHADOW } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.cream,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 160,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: COLORS.midnightNavy,
    textAlign: "center",
  },
  imageContainer: {
    width: "100%",
    height: 256,
    backgroundColor: COLORS.frostGray,
    position: "relative",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imageHidden: {
    opacity: 0,
  },
  imageSkeleton: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.frostGray,
    overflow: "hidden",
  },
  shimmer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: `${COLORS.crimson}20`,
  },
  gradientOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  datePillsContainer: {
    position: "absolute",
    bottom: 16,
    left: 16,
    flexDirection: "column",
    gap: 4,
  },
  datePill: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  datePillText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.white,
  },
  timePill: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  timePillText: {
    fontSize: 11,
    color: COLORS.white,
  },
  locationText: {
    opacity: 0.8,
  },
  eventTypePillContainer: {
    position: "absolute",
    bottom: 16,
    right: 16,
  },
  eventTypePill: {
    backgroundColor: COLORS.auroraGold,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  eventTypePillText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  titleSection: {
    marginBottom: 16,
    paddingHorizontal: 24,
  },
  infoContainer: {
    padding: 24,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    opacity: 0.7,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  eventTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.midnightNavy,
    marginBottom: 12,
    fontFamily: "System",
    textAlign: "center",
    marginBottom: 16,
  },
  badgesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 24,
    justifyContent: "center",
  },
  eventTypeBadge: {
    backgroundColor: COLORS.auroraGold,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  eventTypeBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  detailsGrid: {
    marginBottom: 24,
    gap: 16,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  locationRow: {
    width: "100%",
  },
  dressCodeRow: {
    width: "100%",
  },
  detailText: {
    fontSize: 16,
    color: COLORS.midnightNavy,
    opacity: 0.7,
    flex: 1,
  },
  priceText: {
    color: COLORS.crimson,
    fontWeight: "600",
    opacity: 1,
  },
  dressCodeContainer: {
    flex: 1,
  },
  dressCodeNotes: {
    fontSize: 14,
    color: COLORS.midnightNavy,
    opacity: 0.6,
    marginTop: 4,
    fontStyle: "italic",
  },
  descriptionContainer: {
    marginTop: 24,
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  description: {
    fontSize: 16,
    color: COLORS.midnightNavy,
    opacity: 0.7,
    lineHeight: 24,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.frostGray,
    opacity: 0.5,
    marginTop: 24,
    marginHorizontal: 24,
  },
  promoterContainer: {
    marginTop: 24,
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  promoterCard: {
    backgroundColor: `${COLORS.cream}99`,
    padding: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.frostGray,
  },
  promoterSectionLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    opacity: 0.7,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  promoterContent: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  promoterAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: `${COLORS.midnightNavy}1A`,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 4,
  },
  promoterAvatarText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  promoterInfo: {
    flex: 1,
  },
  promoterNameRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  promoterBadgesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
    marginBottom: 8,
  },
  promoterLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  promoterDisclaimer: {
    fontSize: 12,
    color: COLORS.midnightNavy,
    opacity: 0.6,
    marginTop: 8,
  },
  supportText: {
    fontSize: 12,
    color: COLORS.midnightNavy,
    opacity: 0.7,
  },
  chapterNameBold: {
    fontWeight: "600",
  },
  countdownContainer: {
    marginHorizontal: 24,
    marginVertical: 24,
    backgroundColor: `${COLORS.cream}CC`,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.frostGray,
  },
  countdownLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.midnightNavy,
    marginBottom: 8,
  },
  maxAttendeesText: {
    fontSize: 14,
    color: COLORS.midnightNavy,
    opacity: 0.6,
    marginBottom: 24,
  },
  rsvpButton: {
    marginTop: 8,
  },
  mapContainer: {
    marginTop: 24,
    marginHorizontal: 24,
    marginBottom: 16,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: COLORS.frostGray,
  },
  mapHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: `${COLORS.frostGray}99`,
    backgroundColor: `${COLORS.cream}66`,
  },
  mapHeaderTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    opacity: 0.8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mapHeaderLink: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.crimson,
  },
  mapButton: {
    width: "100%",
  },
  mapPlaceholder: {
    height: 300,
    backgroundColor: `${COLORS.cream}CC`,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  mapText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    marginTop: 12,
  },
  mapLocationText: {
    fontSize: 14,
    color: COLORS.midnightNavy,
    opacity: 0.7,
    marginTop: 8,
    textAlign: "center",
  },
  actionButtonsContainer: {
    marginTop: 8,
  },
  actionButton: {
    width: "100%",
  },
  buttonWithSpacing: {
    marginBottom: 12,
  },
  primaryButton: {
    backgroundColor: COLORS.crimson,
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    ...SHADOW.button,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  shareButton: {
    backgroundColor: COLORS.midnightNavy,
  },
  secondaryButton: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.crimson,
    ...SHADOW.input,
  },
  secondaryButtonText: {
    color: COLORS.crimson,
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  disabledButton: {
    backgroundColor: COLORS.frostGray,
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    opacity: 0.6,
  },
  disabledButtonText: {
    color: COLORS.midnightNavy,
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: 0.3,
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.frostGray,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.midnightNavy,
  },
  modalCloseButton: {
    padding: 4,
  },
  shareOptionsContainer: {
    padding: 20,
  },
  shareOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: `${COLORS.cream}40`,
    marginBottom: 12,
  },
  shareOptionText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    marginLeft: 12,
  },
  shareSectionDivider: {
    height: 1,
    backgroundColor: COLORS.frostGray,
    marginVertical: 20,
  },
  shareSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    opacity: 0.7,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  qrCodeContainer: {
    padding: 20,
    alignItems: "center",
  },
  qrCodeTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.midnightNavy,
    marginBottom: 24,
  },
  qrCodeWrapper: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 12,
    marginBottom: 16,
  },
  qrCodeUrl: {
    fontSize: 12,
    color: COLORS.midnightNavy,
    opacity: 0.6,
    marginBottom: 24,
    textAlign: "center",
  },
  backButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: COLORS.frostGray,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  dressCodeChipWrapper: {
    flexDirection: "row",
    flexWrap: "wrap",
    flex: 1,
    marginHorizontal: -4,
  },
  dressCodeChip: {
    backgroundColor: COLORS.cream,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: COLORS.frostGray,
    marginHorizontal: 4,
    marginVertical: 4,
  },
  dressCodeChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.midnightNavy,
  },
  contentCard: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 24,
    marginTop: -24,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },

  fullImageGradient: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
});
